-- Add the new columns to the Automovil table
ALTER TABLE "public"."Automovil"
ADD COLUMN IF NOT EXISTS "soat" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "revisionTecnomecanica" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "tarjetaOperacion" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "licenciaTransito" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "extintor" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "revisionPreventiva" TIMESTAMP(3) WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "revisionAnual" TIMESTAMP(3) WITH TIME ZONE;
